# Fetch Order after every 15 min
#sync_order:
#  cron: "*/10 * * * *"
#  class: "SyncOrderWorker"
#  queue: default

# Fetch inventory at every 4 hours
#fetch_inventory:
#  cron: "*/20 * * * *"
#  class: "FetchInventoryWorker"
#  queue: default

# Fetch inventory details at every 4:30 hours
#fetch_inventory_details:
#  cron: "*/30 * * * *"
#  class: "FetchInventoryDetailsWorker"
#  queue: default


# Set inventory at 1:30 PM Daily - 250 products
#set_inventory:
#  cron: "*/40 * * * *"
#  class: "SetInventoryWorker"
#  queue: default

# Set inventory images at every 6 hours
#set_inventory_images:
#  cron: "*/55 * * * *"
#  class: "SetInventoryImagesWorker"
#  queue: default

# Set inventory images at every 6 hours
customer_worker:
  cron: "*/55 * * * *"
  class: "CustomerWorker"
  queue: default